openapi: 3.1.0
info:
  title: DriveEz - Authentication API
  description: REST API for user authentication.
  version: 'v1.0'
servers:
  - url: http://localhost:3000
paths:
  /auth/register:
    post:
      summary: User Registration
      description: Register a new user.
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: The username for the new user.
                  example: new_user
                password:
                  type: string
                  description: The password for the new user.
                  example: secret_password
                name:
                  type: string
                  description: The name of the user.
                  example: John Doe
                email:
                  type: string
                  format: email
                  description: The email address of the user.
                  example: john.doe@example.com
                phone:
                  type: string
                  description: The phone number of the user.
                  example: +1234567890
              required:
                - username
                - password
                - name
                - email
                - phone
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Bad Request
                  error_description:
                    type: string
                    example: User with the provided username already exists

  /auth/login:
    get:
      summary: User Login
      description: Obtain an access token for authentication.
      operationId: loginUser
      parameters:
        - name: username
          in: query
          description: The username of the user.
          required: true
          schema:
            type: string
          example: amisha_bhawsar
        - name: password
          in: query
          description: The user's password.
          required: true
          schema:
            type: string
          example: secret_password
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: The access token for authentication.
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
                  token_type:
                    type: string
                    description: The type of the token.
                    example: Bearer
                  expires_in:
                    type: integer
                    description: The duration in seconds for which the access token is valid.
                    example: 3600
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unauthorized
                  error_description:
                    type: string
                    example: Invalid credentials

  /auth/logout:
    post:
      summary: User Logout
      description: Invalidate the access token to log the user out.
      operationId: logoutUser
      parameters:
        - name: access_token
          in: query
          description: The access token to be invalidated.
          required: true
          schema:
            type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
      responses:
        '204':
          description: Successful logout
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unauthorized
                  error_description:
                    type: string
                    example: Invalid token
